import os
import glob
import pandas as pd
from snakemake.utils import validate, min_version

##### set minimum snakemake version #####
min_version("6.4.1")

##### load global variables and functions #####
include: "rules/globals.smk"
include: "rules/functions.smk"

##### load config #####
configfile: "config/config.yaml"
validate(config, schema="schema/config.schema.yaml")

##### load metadata #####
Metadata = pd.read_table(config["metadata"])
validate(Metadata, schema="schema/metadata.schema.yaml")

##### set up variables #####
types = config["types"]
templates = {"all": "all", "unique": "unique", "set": "set"}

##### import the rest of the rules #####
include: "rules/preprocess_data.smk"
include: "rules/export_analysis_types.smk"
include: "rules/cluster_profiler.smk"
if len(pd.unique(Metadata.contrast)) > 1 and config["set_analysis"]:
    include: "rules/cluster_profiler_sets.smk"
    #include: "rules/cluster_profiler_multi.smk"
else:
    include: "rules/skip_cluster_profiler_sets.smk"
    # include: "rules/skip_cluster_profiler_multi.smk"
# include: "rules/copy_config.smk"
# include: "rules/create_archive.smk"

# TODO clustercompare
# TODO enrichr libraries https://maayanlab.cloud/Enrichr/#libraries
# TODO heatplot scale warning
# TODO venn diagram is broken
# TODO 4: It looks like Source/Target is not zero-indexed. This is required in JavaScript and so your plot may not render.
# TODO also breaks figure legend
# TODO archive also bundles the results folder
rule all:
    input:
        get_preprocess_data_files,
        get_cp_output,
        get_cp_csv_output,
        get_cp_report_output,
        get_cp_unique_output,
        get_cp_unique_csv_output,
        get_cp_unique_report_output,
        # get_copy_config_files,
        # get_heatmap_output_files,
        # get_archive_output_files
        
        
