import os
import glob
import pandas as pd
from snakemake.utils import validate, min_version

##### set minimum snakemake version #####
min_version("6.4.1")

##### load global variables and functions #####
include: "rules/globals.smk"
include: "rules/functions.smk"

create_directory(OUTPUT_DIR)
create_directory(CSV_OUTDIR)

##### load config #####
configfile: "config/config.yaml"
validate(config, schema="schema/config.schema.yaml")

##### load metadata #####
Metadata = pd.read_table(config["metadata"])
validate(Metadata, schema="schema/metadata.schema.yaml")

##### import the rest of the rules #####
types = config["types"]
if len(pd.unique(Metadata.contrast)) == 1:
    templates = ['contrast']
else:
    templates = ['contrast', 'unique']

include: "rules/export_analysis_types.smk"
include: "rules/cluster_profiler.smk"
if len(pd.unique(Metadata.contrast)) > 1:
    include: "rules/cluster_profiler_multi.smk"
else:
    include: "rules/skip_cluster_profiler_multi.smk"
include: "rules/create_heatmaps.smk"
include: "rules/copy_config.smk"
include: "rules/create_archive.smk"

# TODO clustercompare
# TODO enrichr libraries https://maayanlab.cloud/Enrichr/#libraries
# TODO heatplot scale warning

rule all:
    input:
        get_cp_output_files,
        get_cp_multi_output_files,
        get_copy_config_files,
        get_heatmap_files,
        get_archive_output_files,
        
        
