---
title: "`r paste0(payloads_sub$type[1], ' - ', stringr::str_trunc(outdir, 25))`"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: paper
---

```{r setup, include=FALSE, cache=FALSE}
# Set knitr options to allow duplicate labels (needed for the subpages)
options(knitr.duplicate.label = "allow")
#knitr::opts_knit$set(root.dir = normalizePath(".."))
scrolly_dt <- 800
```

```{r prepare_data}
if (template == "contrast") {
  set_overview <- FALSE
} else {
  input_contrast <- outdir
  set_overview <- TRUE
}
```

```{r css, echo=FALSE, results='asis', eval = T}
# fix for datatable height in flexdashboard
cat(glue(.open = "<<", .close = ">>", "
<style>
.dataTables_scrollBody {
    height: <<scrolly_dt>>px !important;
    max-height: <<scrolly_dt>>px !important;
}
</style>
"))
```

# Overview

Column {.tabset .tabset-fade data-width=225}
-----------------------------------------------------------------------

```{r child = 'scripts/description.Rmd', eval = T}
```

Column {data-width=275}
-----------------------------------------------------------------------

```{r child = 'scripts/volcano.Rmd', eval = T}
```

<!-- conditional evaluation of graph based on whether it's set or contrast -->
```{r child = 'scripts/venn.Rmd', eval = !set_overview}
```

```{r child = 'scripts/venn.Rmd', eval = set_overview}
```

Column {data-width=150}
-----------------------------------------------------------------------

```{r child = 'scripts/valuebox_info.Rmd', eval = T}
```

Column {data-width=350}
-----------------------------------------------------------------------

```{r child = 'scripts/gene_expr_table.Rmd', eval = T}
```

<!-- render subpages with pathway data -->
```{r include = F, eval = T}
out <- map_if(
  subpage_data,
  is.not.empty.list,
  ~ create_subpage_markdown(.x),
  .else = ""
)
```

`r paste(knitr::knit_child(text = out), collapse = '')`
