# path to pandoc executable on your system
pandoc_path: "/usr/lib/rstudio-server/bin/quarto/bin/tools"

experiment_name: "gpr35_ga"

# relative path to root directory of the workflow
metadata: "config/metadata.tsv"
species: "mouse"
create_archive: "yes"

# Whether clusterProfiler should be run on unique and common genes between the
# specified lists of differentially expressed genes.
# When doing more complicated comparisons between groups, this should be ideally
# reflected in your design for analysis of differential gene expression. 
# When that is not possible, set analysis could be used instead.
set_analysis: TRUE

# should the html output be self contained or have a separate lib directory
# separate lib directory saves space, but individual html files can't be shared
self_contained: FALSE

# any combination of:
# Disease, GeneOntology, MSigDB, MSigDB_cancer, MeSH_g2p, MeSH_gendoo,
# Pathways, ConsensusPathDB
types:
  - "Pathways"

# name of the gene ID column in the deg file
id_column_name: "ENSEMBL"

# type of ID column in the deg file
# Must be one of supported by org.db
id_type: "ENSEMBL"

# other column names needed for clusterProfiler analysis
fc_column_name: "log2FoldChange"
padj_column_name: "padj"
pval_column_name: "pvalue"

# fc and adjusted pvalue filtering of input data
gene_fc_threshold: 0.585
gene_padj_threshold: 0.05

# parameters for cluster profiler enrich and gse family of functions
enrich_minGS: 10
enrich_maxGS: 200
enrich_pval_cutoff: 0.05
go_simplify_cutoff: 0.7
gse_minGS: 10
gse_maxGS: 200
gse_pval_cutoff: 0.25

# minimum number of genes in individual unique upset sets for analysis
min_set_size: 50

# max number of categories shown in plots
max_categories:
  dotplot: 40
  networkplot: 20
  heatplot: 20
  enrichmap: 35

# hide columns from clusterProfiler table output
table:
  hide_columns: ["BgRatio", "qvalue", "qvalues", "leading_edge"]

# which analysis include or exclude when creating heatmaps
# include and exclude categories are exclusive
# if left empty, heatmaps for all pathways will be created
heatmaps:
  # list of text files with pathway ids to generate heatmaps for (one ID per line)
  # if specified overrides all subsequent include/exclude settings
  pathway_id_files: []
  # specified in 'types'
  type:
    include: []
    exclude: []
  # list of available categories, see 'workflow/scripts/export_analysis_types.R'
  # for more details
  category:
    include: []
    exclude: []
  # 'ORA' of 'GSEA' or both
  analysis: []


  